# BPS config file version ?

pools:

  '231215':
    plasmids:
      - paSL6
    demux: |
      barcode01	GPCR1
      barcode02	GPCR2
      barcode03	GPCR3
      barcode04	GPCR4
      barcode05	GPCR5
      barcode06	GPCR6
      barcode07	GPCR7
      barcode08	GPCR8
      barcode09	GPCR9
      barcode10	GPCR10
      barcode11	GPCR11
      barcode12	GPCR12
      barcode13	GPCR13
      barcode14	GPCR14
      barcode15	GPCRpool-1-1
      barcode16	GPCRpool-1-2
      barcode17	GPCRpool-2-1
      barcode18	GPCRpool-2-2
      barcode19	paSL6-A1
      barcode20	paSL6-A2
      barcode21	paSL6-B1
      barcode22	paSL6-B2
      barcode23	eaBSD2-1
      barcode24	eaBSD2-2
      barcode25	eaBSD2-3
      barcode26	eaBSD2-4
      barcode27	eaBSD2-5
      barcode28	eaBSD2-6
      barcode29	eaBSD2-7
      barcode30	eaBSD2-8
      barcode31	eaBSD2-9
      barcode32	eaBSD2-10
      barcode33	eaBSD2-11
      barcode34	eaBSD2-12

plasmids:

  paSL6: 
    signature: 'ATGTTACGCAGCAGCAACGATGTTACGCAGCAGGGCAGTCGCCCTAAAACAAAGTTAGGTGGCTCAAGTATGGGCATCATTCGCACATGTAGGCTCGGCCCTGACCAAGTCAAATCCATGCGGGCTGCTCTTGATCTTTTCGGTCGTGAGTTCGGAGACGTAGCCACCTACTCCCAACATCAGCCGGACTCCGATTACCTCGGGAACTTGCTCCGTAGTAAGACATTCATCGCGCTTGCTGCCTTCGACCAAGAAGCGGTTGTTGGCGCTCTCGCGGCTTACGTTCTGCCCAAGTTTGAGCAGCCGCGTAGTGAGATCTATATCTATGATCTCGCAGTCTCCGGCGAGCACCGGAGGCAGGGCATTGCCACCGCGCTCATCAATCTCCTCAAGCATGAGGCCAACGCGCTTGGTGCTTATGTGATCTACGTGCAAGCAGATTACGGTGACGATCCCGCAGTGGCTCTCTATACAAAGTTGGGCATACGGGAAGAAGTGATGCACTTTGATATCGACCCAAGTACCGCCACCTAACAATTCGTTCAAGCCGAGATCGGCTTCCCGGCCGCGGAGTTGTTCGGTAAATTGTCACAACGCC' # this is the gentamicin marker

runs:

  20231031_1251_MN24357_FAX05725_1738ecc6:
    fastq: '/archive/l/seq_data/bps/20231215_1356_MN24328_FAY03346_aabaabf9/basecalling/output/demuxed.fastq.gz'
    flowcell: 'FLO-MIN114'
    pool: '231215'
    medaka-model: 'r1041_e82_400bps_sup_v4.2.0'

#####

samlami-paSL6-bc: &samlami-paSL6-bc
  - arg: '--cut-on-left'
    ref: 'ggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtg'
  - arg: '--cut-on-right'
    ref: 'ccattgagtaagtttttaagcacatcagcttcaaaagcCTGCGAGGGCTA'

samlami-eaBSD1-dbc: &samlami-eaBSD1-dbc
  - arg: '--cut-on-left'
    ref: 'gcggccaattcgatctagaattccattgagtaagtttttaagcacatcagcttcaaaagcCTGCGAGGGCTAGAATTACCTACCGGCCTC'
  - arg: '--cut-on-right'
    ref: 'GTAAGGGTATAAAGTTGCAACCGTCCCCCAAGCGTACAGGGTGCACTTTGTAACGATTTGGGAGTCCAAAGACTCGCTGTTTTCGAAATTTGCCCTCAAG'

samlami-paSL6-payload: &samlami-paSL6-payload
  - arg: '--cut-on-left'
    ref: 'gcggccaattcgatctagaattccattgagtaagtttttaagcacatcagcttcaaaagcCTGCGAGGGCTAGAATTACC'
  - arg: '--cut-on-right'
    ref: 'AGGACTAGTACGCGcgataagcttgatatcgaattcccccgggaccaaaatggcaagtaaaatagcctgatgggataggctctaagtccaacgaaccagt'

experiments: 

  tak-reannotate-paSL6:
    pools:
      - '231215'
    filter-out: 'config/filter-out-r6k-psc101.fasta'
    plasmids:
      - paSL6
    include-samples:
      - paSL6-A1
      - paSL6-A2
      - paSL6-B1
      - paSL6-B2
    extract-barcode:
      paSL6:
        samlami: *samlami-eaBSD1-dbc
        itermae: 'config/itermae_donor_barcode_eaBSD1.yaml'
        knowncodes: 'config/eaBSD1_barcodes.fasta'
    assembly-method: flye
    post-assembly:
      recipient-barcode: 
        samlami: *samlami-paSL6-bc
        itermae: 'config/itermae_BC_paSL6.yaml'
        target-fasta: 'config/paSL6_recipient_barcodes.fasta'
        target-size: 'short'

  tak-annotate-eaBSD2:
    pools:
      - '231215'
    filter-out: 'config/filter-out-r6k-psc101.fasta'
    plasmids:
      - paSL6
    include-samples:
      - eaBSD2-1
      - eaBSD2-2
      - eaBSD2-3
      - eaBSD2-4
      - eaBSD2-5
      - eaBSD2-6
      - eaBSD2-7
      - eaBSD2-8
      - eaBSD2-9
      - eaBSD2-10
      - eaBSD2-11
      - eaBSD2-12
    extract-barcode:
      paSL6:
        samlami: *samlami-eaBSD1-dbc
        itermae: 'config/itermae_donor_barcode_eaBSD1.yaml'
        knowncodes: 'config/eaBSD1_barcodes.fasta'
    assembly-method: flye
    post-assembly:
      recipient-barcode: 
        samlami: *samlami-paSL6-bc
        itermae: 'config/itermae_BC_paSL6.yaml'

  tak-analyze-gpcr:
    pools:
      - '231215'
    filter-out: 'config/filter-out-r6k-psc101.fasta'
    plasmids:
      - paSL6
    include-samples:
      - GPCR1
      - GPCR2
      - GPCR3
      - GPCR4
      - GPCR5
      - GPCR6
      - GPCR7
      - GPCR8
      - GPCR9
      - GPCR10
      - GPCR11
      - GPCR12
      - GPCR13
      - GPCR14
    extract-barcode:
      paSL6:
        samlami: *samlami-paSL6-bc
        itermae: 'config/itermae_BC_paSL6.yaml'
        knowncodes: 'config/all_possible_paSL6.fasta'
    assembly-method: flye
    post-assembly:
      payload:
        samlami: *samlami-paSL6-payload
        itermae: 'config/itermae_payload_paSL6.yaml'
        target-fasta: 
          - 'config/gpcr-segments.fasta'
          - 'config/All_6_GPCR_combinations.fasta'
        target-size: 'long'
      rotate: 
        samlami:
          - arg: '--modulus'
            ref: 'GCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTATAGTCCGGAAATACAGGAACGC'
            head: 100
        annotate: 
          - 'config/gpcr-segments.fasta'
          - 'config/pSL1227.fasta'

