---
title: 'Analysis of LASSO library intended for the rearray'
author: 'Darach Miller'
date: '`r Sys.Date()`'
theme: 'simplex'
params:
    base_script: 'bps_base_calls.R'
---

```{r,read_in_datar_with_base_script,cache=T,cache.lazy=F}
#rmarkdown::render("bps_calls.Rmd",output_dir=getwd(),knit_root_dir=getwd())

message("Running a base script for handy functions, reading in inputs properly")
source(params$base_script)
```

```{r,summarize,cache=T}

g <- pay2polpay_alns %>% 
    group_by(sample,plate) %>% 
    tally() %>% arrange(-n) %>% 
    filter(plate!="unknown") %>%
    order_sample_names %>%
    ggplot()+theme_bw()+
    aes(x=sample,y=n,col=plate)+
    geom_point()+
    scale_y_continuous(limits=c(0,NA))+
    theme(axis.text.x=element_text(angle=90))+
    ylab("Usable reads per sample, plate")+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_reads_per_sample.jpeg"),g,width=7,height=5)

g <- payloads_datar %>%
    group_by(sample,plate) %>% 
    tally() %>% arrange(-n) %>% 
    filter(plate!="unknown") %>%
    order_sample_names %>%
    ggplot()+theme_bw()+
    aes(x=sample,y=n,col=plate)+
    geom_point()+
    scale_y_continuous(limits=c(0,384))+
    theme(axis.text.x=element_text(angle=90))+
    ylab("Payloads polished")+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_payloads_per_sample.jpeg"),g,width=7,height=5)

g <- pay2polpay_alns %>% 
    group_by(sample,plate) %>% 
    tally(name='reads') %>%
    left_join(
        payloads_datar %>%
            group_by(sample,plate) %>% 
            tally(name='payloads')
        ,by=c('sample','plate')) %>%
    filter(plate!="unknown") %>%
    {
    ggplot(.)+theme_bw()+
    aes(x=reads,y=payloads,label=sample,col=plate)+
    geom_point()+
    geom_text_repel(
        data=mutate(.,cutoff=quantile(.$payloads[.$payloads>50],0.1)) %>%
            filter(payloads>50,payloads<cutoff),
        max.overlaps=12)+
    scale_y_continuous(limits=c(0,384))+
    ylab("Payloads polished")+
    xlab("Usable reads per sample")+
    NULL
    }
g

ggsave(paste0(this_id,"_",Sys.Date(),"_reads_vs_payloads_per_sample.jpeg"),g,width=7,height=5)

g <- pay2ref_alns %>% 
    group_by(sample,plate) %>% 
    filter(plate!="unknown") %>%
    mutate(frac_match=aln_score/length) %>%
    {
    ggplot(.)+theme_bw()+
    aes(x=sample,y=frac_match,col=plate)+
    facet_wrap(~plasmid,scales="free")+
    geom_violin()+
    scale_y_log10(limits=c(0.9,1))+
    theme(axis.text.x=element_text(angle=90))+
    #scale_y_continuous(limits=c(0,384))+
    #ylab("Payloads polished")+
    #xlab("Usable reads per sample")+
    NULL
    }
g

ggsave(paste0(this_id,"_",Sys.Date(),"_fraction_matching_per_sample.jpeg"),g,width=7,height=5)

g <- pay2ref_alns %>% 
    group_by(sample,plate) %>% 
    filter(plate!="unknown",plasmid=='1064x937') %>%
    mutate(frac_match=aln_score/length) %>%
    {
    ggplot(.)+theme_bw()+
    aes(x=frac_match)+
    facet_wrap(~plasmid,scales="free")+
    geom_histogram(bins=200)+
    scale_x_log10(limits=c(0.99,1))+
    #scale_y_continuous(limits=c(0,384))+
    #ylab("Payloads polished")+
    #xlab("Usable reads per sample")+
    NULL
    }
g

ggsave(paste0(this_id,"_",Sys.Date(),"_fraction_matching_top_1_percent.jpeg"),g,width=7,height=5)


```

```{r,how_do_assemblies_look,cache=T}

g<- match_to_ref %>%
    filter(plate!="unknown") %>%
    left_join(med_length,by='sample') %>%
    ggplot()+theme_classic()+
    aes(x=interaction(plate,row,col),y=polished_length)+
    geom_point()+
    geom_hline(aes(yintercept=median_length),col="red",linetype="dashed")+
    facet_wrap(~sample,scales='free',
        labeller=function(x){label_both(x,multi_line=F)})+
    xlab('each well')+
    ylab('length of polished payload\n( red line is median )')+
    scale_y_continuous(limits=c(0,NA))+
    theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_bps_length_polished_per_well.jpeg"),g,width=8,height=16)

```

# Purity - are the wells mixed?

```{r,purity_plots,cache=T}

g <- well_purity %>%
    select(experiment,sample,plate,plasmid,row,col,n_queries) %>%
    distinct() %>% 
    ggplot()+theme_classic()+
    aes(x=n_queries,group=interaction(plasmid,experiment,sample,plate),
        col=interaction(plasmid,sample))+
    #guides(col='none')+
    stat_density(geom="line",aes(y=..count..),position="identity",alpha=0.5)+ 
    scale_x_log10("reads per well")+#limits=c(0.5,NA))+
    #facet_wrap(~experiment+sample+plate,scales="free_y",labeller=labeller(label_both,.multi_line=F))+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_number_of_reads_per_well.jpeg"),g,width=7,height=5)

g <- well_purity %>%
    select(experiment,sample,plate,plasmid,row,col,f_score,n_queries) %>%
    distinct() %>% 
    ggplot()+theme_classic()+
    aes(x=f_score,col=n_queries>=10)+
    #geom_histogram(breaks=seq(-0.005,1.005,0.003))+
    stat_bin(geom='line',position='identity',breaks=seq(-0.005,1.005,0.003))+
    scale_x_log10(limits=c(0.5,1))+
    scale_y_log10()+
    facet_wrap(~sample,scales="free",labeller="label_both")+
    xlab('fractional identity of each raw payload with polished consensus')+
    NULL
g

g <- well_purity %>%
    select(experiment,sample,plate,plasmid,row,col,f_score,n_queries) %>%
    distinct() %>% 
    ggplot()+theme_classic()+
    aes(x=f_score)+
    geom_histogram(breaks=seq(-0.005,1.005,0.003))+
    scale_x_log10(limits=c(0.7,1))+
    facet_wrap(~n_queries>=30,scales="free",labeller="label_both")+
    xlab('fractional identity of each raw payload with polished consensus')+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_fscore_for_low_coverage_payloads.jpeg"),g,width=7,height=5)

g <- pay2polpay_alns %>%
    group_by(experiment,plasmid,sample,code,plate,row,col) %>%
    summarize(
        mean_fscore=mean(f_score),
        median_fscore=median(f_score),
        n_queries=unique(n_queries)
        ) %>%
    ggplot()+theme_classic()+
    aes(y=median_fscore,x=n_queries)+
    geom_density_2d()+
    geom_point(size=0.2,alpha=0.2)+
    scale_x_log10()+
    scale_y_log10(limits=c(0.4,1))+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_fscore_over_coverage.jpeg"),g,width=7,height=5)

```

The below is just trying to get at a threshold

```{r,intuition_please,cache=T}

g<- well_purity%>% filter(!is.na(plate))  %>% 
    filter(plasmid==plasmid[1]
        ,sample==sample[1]
        ,plate=="A"
        ,row%in%c("A","B","C")
        #,col%in%c(12,13,14)
        ) %>% #,"B","C","D","E","F","G","H"
    #mutate(correct_length=(length==med_length)) %>%
    {
    ggplot(.)+theme_classic()+
    aes(col=interaction(sample,plate,row,col),x=f_score)+
    stat_density(geom="line",position="identity")+
    facet_grid(sample~row,scales="free",
        labeller=label_both)+ 
    guides(col='none')+
    scale_x_log10(limits=c(0.7,1.0))+
    geom_vline(data=ungroup(.) %>% dplyr::select(plate,sample,row,col) %>% 
            mutate(f_score=list(c(.85,.9,.95,.98)),row=NA,col=NA) %>%
            unnest(f_score) %>%
            mutate(row=list(c("A","B","C"))) %>% unnest(row) %>%
            distinct() ,
        aes(xintercept=f_score))+
    geom_label(data=ungroup(.) %>% dplyr::select(plate,sample,row,col) %>% 
            mutate(f_score=list(c(.85,.9,.95,.98)),row=NA,col=NA) %>%
            unnest(f_score) %>%
            mutate(row=list(c("A","B","C"))) %>% unnest(row) %>%
            distinct() ,
        aes(label=f_score),y=0)+
    NULL
    }
g

ggsave(paste0(this_id,"_",Sys.Date(),"_bps_example_scores_three_rows.jpeg"),g,width=7,height=5)

```

```{r,decide_yo,cache=T,cache.lazy=F}

pdatar <- well_purity %>%
    filter(!is.na(plate))%>%
#    mutate(
#        aberrant_length= length!=med_length
#        ) %>%
    group_by(experiment,sample,plate,row,col) 
pdatar

# cutoff threshold
quantile_depth <- quantile(pdatar$n_queries,probs=.01)
cutoff_for_depth <- max(5,quantile_depth)

pdatar %>% 
    ggplot()+theme_bw()+
    aes(x=n_queries)+
    geom_histogram(bins=200)+ 
    geom_vline(xintercept=quantile_depth,col="blue",lty="dashed")

pdatar %>% 
    ggplot()+theme_classic()+
    #aes(col=aberrant_length,x=f_score)+
    aes(x=f_score)+
    stat_density(geom="line",position="identity",adjust=0.1)+
    geom_vline(xintercept=c(0.85,.9,.95))+
    scale_x_log10(limits=c(0.5,1.0),
        breaks=seq(0.5,1,.05),labels=seq(0.5,1,.05))+
    NULL

print("use 0.90 identity i guess")

pdatar %>% 
    #filter(!aberrant_length) %>% 
    mutate(on_target=f_score>0.90) %>%
    group_by(experiment,sample,plate,row,col,n_queries) %>%
    summarize(purity=sum(on_target)/length(on_target)) %>%
    ggplot()+theme_classic()+
    aes(x=purity)+
    geom_histogram(bins=200)+
    facet_wrap(~n_queries>=cutoff_for_depth,labeller="label_both")+
    scale_x_continuous(breaks=seq(0.0,1,.10),labels=seq(0.0,1,.10))+
    xlab("Fraction of reads per well agreeing with consensus")+
    ylab("Count of wells")+
    NULL

```

That last one shows us that totally pure calls are likely just by chance not
sampling the minor variant per well. 
    

```{r,setupCalledAllAndOutput,cache=T}

called_all <- well_purity %>%
    filter(sample!="") %>%
    filter(!is.na(plate)) %>% 
    group_by(experiment,sample,plate,row,col,code) %>%
    mutate( main_plasmid=plasmid[order(n_queries,decreasing=T)[1]],) %>%
    mutate(on_target=f_score>0.90 ) %>% 
    mutate( purity=sum(on_target)/length(on_target) ) %>%
    ungroup() %>%
    select(
        -nm,
        -starts_with("cig_"),
        -starts_with("md_"),
        -starts_with("X"),
        -score,-q_length,-f_score,-on_target
        ) %>%
    left_join(
        match_to_ref %>% 
            select(experiment,plasmid,sample,plate,row,col,code,
                target,nm,
                starts_with("cig_"),
                starts_with("md_")
                ) %>%
            distinct()
        ,by=c('experiment','plasmid','sample','plate','row','col','code')
        ) %>% 
    group_by(experiment,plasmid,sample,plate,row,col,code) %>%
    #mutate( main_target=target[order(n_queries,decreasing=T)[1]] ) %>%
    rename(sequence=seq,coverage=n_queries) %>%
    arrange(experiment,sample,plate,row,col,nm) %>% 
    filter(!is.na(sequence)) %>%
    distinct() %>%
    left_join(
        pay2ref_alns %>% 
            mutate(first_gap=map(payload_seq,function(x){
                        suppressWarnings(min(which(str_split(x,"",simplify=T)=='-')))
                    })) %>%
            mutate(full_length=(first_gap>=(length-3)&aln_score>=0.9*length)) %>%
            ungroup() %>%
            select(experiment,plasmid,sample,plate,row,col,code,full_length) %>%
            distinct()
        ,by=c('experiment','plasmid','sample','plate','row','col','code')
        ) %>% 
    group_by(experiment,sample,plate,row,col,code) %>%
    mutate(
        matched= nm==0 & target != '*' ,
        pure = purity>0.90 & coverage>=cutoff_for_depth,
        total_coverage=sum(coverage),
        ) %>%
    ungroup() %>% 
    #mutate(group=0) %>%
    arrange(experiment,sample,plate,row,col) %>%
    #mutate(sample_group=ifelse(grepl("lasso",sample),'lasso','donorbarcode')) %>%
    select(
        experiment,
        plasmid,
        sample,
        plate,
        row,
        col,
        code,
        target,
        coverage,
        mismatches=nm,
        full_length,
        purity,
        sequence
        ) 
called_all

# Any multiple assemblies per position?
called_all %>% 
    group_by(experiment,sample,plate,row,col) %>%
    filter(length(cur_group_rows())>1)

called_all %>% 
    {names(.) <- str_c(names(.),seq_along(names(.)),sep='_');.}

called_all %>% 
    group_by(purity>0.9,mismatches==0,full_length) %>%
    tally()

called_all %>% 
    {names(.) <- str_c(names(.),seq_along(names(.)),sep='_');.} %>%
    write_csv(paste0(this_id,"_",Sys.Date(),"_bps_calls.csv"))

```

```{r,dubs,cache=T}

called_all %>% 
    filter(purity > 0.9,mismatches==0) %>%
    group_by(sample,plate,row,col,plasmid) %>% 
    tally() %>% arrange(-n)

called_all %>% 
    group_by(sample,plate,row,col,plasmid) %>% 
    tally() %>% arrange(-n,sample,plate,row,col,plasmid)

called_all %>% 
    filter(purity > 0.9) %>% 
    group_by(sample,plate,row,col) %>% 
    tally() %>% arrange(-n,sample,plate,row,col)

```

```{r,analyze weiyibps,cache=T}

called_all %>% 
    filter(purity > 0.9) 

called_all %>% 
    group_by(target) %>% 
    tally() %>% arrange(-n) 

called_all %>% 
    filter(purity > 0.9,full_length,mismatches==0) %>%
    group_by(target) %>% 
    tally() %>% arrange(-n) 

g <- called_all %>%
    mutate(pure=purity > 0.9) %>%
    filter(pure,full_length,mismatches==0) %>%
    group_by(target,pure) %>% 
    tally() %>%
    ggplot()+theme_bw()+
    aes(x=n)+
    geom_histogram(binwidth=1)+
    #facet_wrap(~pure,labeller=label_both)+
    #scale_x_log10()+
    xlab("pure & full-length matched clones recovered per payload")
g

ggsave(paste0(this_id,"_",Sys.Date(),"_clones_per_payload.jpeg"),g,width=7,height=5)

g <- called_all %>%
    mutate(pure=purity > 0.9,matched=mismatches==0) %>%
    filter(pure,full_length,matched) %>%
    group_by(plasmid,experiment,sample,target,pure) %>%
    tally() %>%
    ggplot()+theme_bw()+
    aes(x=interaction(factor(plasmid),factor(experiment),factor(sample)), y=n)+
    xlab("Clones recovered per target")+
    scale_y_log10()+
    theme(axis.text.x=element_text(angle=90))+
    NULL
g+geom_line(
    aes(group=interaction(factor(plasmid),factor(experiment),factor(target))) ,
        alpha=0.2
        )

ggsave(paste0(this_id,"_",Sys.Date(),"_clones_per_payload_by_sample_line.jpeg"),
    g+geom_line(
        aes(group=interaction(factor(plasmid),factor(experiment),factor(target))) ,
            alpha=0.2
            )
    ,width=7,height=5)

g <- called_all %>%
    filter(plate!="unknown") %>%
    ungroup() %>%
    filter(sample %in% head(unique(sample),2)) %>%
    mutate(polished_errors=ifelse(
            is.na(mismatches),
            "unknown payload",
            ifelse(
                full_length,
                ifelse(
                    mismatches>0 ,
                    ifelse(mismatches>3,"more than 3 errors","1-3 errors"),
                    "perfect")
                ,"truncated"
                )
            )
        ) %>%
    mutate(polished_errors=factor(polished_errors,
                levels=sort(unique(polished_errors)))) %>%
    mutate(pure=ifelse(purity>0.9,"clonal","mixed")) %>%
    mutate(summary_label=paste0(pure," and ",polished_errors)) %>%
    mutate(summary_label=factor(summary_label,levels=sort(unique(summary_label)))) %>%
    mutate(summary_label=relevel(factor(summary_label),"clonal and perfect")) %>% 
    mutate(row=factor(as.character(row),levels=rev(toupper(letters)))) %>%
    ggplot()+theme_classic()+
    aes(x=col,y=row,fill=summary_label)+
    geom_tile()+
    facet_wrap(~experiment+sample+plate,labeller=labeller(label_both,.multi_line=F))+
    theme(legend.position="right")+
    scale_color_discrete("Colony call:")+
    NULL
g

ggsave(paste0(this_id,"_",Sys.Date(),"_bps_errors_plate.jpeg"),g,width=7,height=5)

```

